server:
  port: 8080

spring:
  application:
    name: case6-consumer

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kafka_demo}
    username: ${SPRING_DATASOURCE_USERNAME:kafka_user}
    password: ${SPRING_DATASOURCE_PASSWORD:kafka_pass}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  chaos:
    failure-rate: ${APP_CHAOS_FAILURE_RATE:0.0}
