server:
  port: 8080

spring:
  application:
    name: case4-partition-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      # Все 3 инстанса — одна group. Kafka назначит каждому свою партицию.
      group-id: partition-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true

app:
  instance-id: ${INSTANCE_ID:instance-1}
